using System;
using System.Drawing;
using Sartini_Matteo;

namespace Prete_Giovanni
{
    /// <summary>
    /// This class models an Entity that can move and performs actions.
    /// </summary>
    internal class ActiveEntity : IEntity
    {
        private int _height;
        private int _width;
        private double _xSpeed;
        private double _ySpeed;
        private double _maxYSpeed;

        /// <summary>
        /// Property to get and set the renderer.
        /// </summary>
        public IRenderer Renderer { get; set; }

        /// <summary>
        /// Property to get and set the Transform.
        /// </summary>
        public ITransform Transform { get; set; }

        /// <summary>
        /// Property to get and set the hitbox.
        /// </summary>
        public Nanni_Denise.IHitbox Hitbox { get; set; }

        /// <summary>
        /// Property to get and set the health.
        /// </summary>
        public Nanni_Denise.IHealth Health { get; set; }

        public ActiveEntity(ITransform transform, int height, int width, IRenderer renderer) 
        {
            Transform = transform;
            _height = height;
            _width = width;
            Renderer = renderer;

            _maxYSpeed = 10;
        }
        
        /// <summary>
        /// Initializes the entity.
        /// </summary>
        public void Init()
        {
        }

        /// <summary>
        /// This method checks if the entity is displayed in the game window.
        /// </summary>
        /// <param name="position">position of the player</param>
        /// <returns>true if the entity is close enough to the player in order</returns>
        public bool IsDisplayed(PointF position)
        {
            return Math.Abs(PointF.Subtract(Transform.Position, new SizeF(position.X, position.Y)).X) - _width / 2.0 < Window.Width / 2
                && Transform.Position.Y < Window.Height
                && Transform.Position.Y >= 0;
        }


        /// <summary>
        /// This method is used to render the entity.
        /// </summary>
        /// <param name="position">position of the entity</param>
        /// <returns>the Renderable generated by the renderer which
        /// will be given as input to the Scene</returns>
        public IRenderable Render(PointF position) => Renderer.Render(position, 0);

        /// <summary>
        /// This method checks if the entity should be updated based on
        /// its position and the distance from the position of the player.
        /// </summary>
        /// <param name="position">the position of the player</param>
        /// <returns>true if the entity should be updated,
        /// false otherwise</returns>
        public bool IsUpdated(PointF position) 
        {
            return Math.Abs(PointF.Subtract(Transform.Position,
                new SizeF(position)).X) < Window.Width;
        }

        /// <summary>
        /// Checks if the Entity is jumping.
        /// </summary>
        /// <returns>true if the y position of the entity is over the ground level,
        /// false otherwise</returns>
        protected bool IsJumping() => Transform.Position.Y > Transform.GroundLevel;

        /// <summary>
        /// Takes as input an element of Inputs enum and,
        /// from that, the class will do the update.
        /// </summary>
        /// <param name="inputs">an element of the enum</param>
        public void Update(Inputs inputs)
        {
            switch (inputs)
            {
                case Inputs.LEFT:
                    _xSpeed = -10;
                    break;
                case Inputs.RIGHT:
                    _xSpeed = 10;
                    break;
                case Inputs.SPACE:
                    _ySpeed = 10; 
                    break;
                case Inputs.EMPTY:
                        Transform.Move((float) _xSpeed, (float) _ySpeed);
                        _xSpeed = Acceleration.Accelerate(_xSpeed, 0, 0.5);
                        _ySpeed = this.IsJumping()
                                ? Acceleration.Accelerate(_ySpeed, -_maxYSpeed, 1) : 0;
                        Transform.ResetGroundLevel();
                    break;
                default:
                    throw new Exception();
            }
        }
    }
}
